name = "KEEP"
uuid = "43413fff-ad5b-4266-9485-4ac3dd215f36"
version = "0.1.0"
authors = ["Antonin Bavoil <antonin.bavoil@univ-cotedazur.fr>"]

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StrFormat = "b5087856-efa9-5a6d-8e6f-97303a7af894"

[compat]
ADNLPModels = "0.8.13"
ADTypes = "1.20.0"
ComponentArrays = "0.15.30"
DiffEqCallbacks = "4.10.1"
DiffResults = "1.1.0"
ForwardDiff = "1.3.0"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
Logging = "1.11.0"
NLPModelsIpopt = "0.11.1"
NaNMath = "1.1.3"
NonlinearSolve = "4.12.0"
OrdinaryDiffEqTsit5 = "1.6.0"
Plots = "1.41.3"
Setfield = "1.1.2"
SplitApplyCombine = "1.2.3"
StaticArrays = "1.9.15"
StrFormat = "1.0.1"
julia = "1.10"
